Datasets details dialog
ConservationInternational/trends.earth pull request #440
Opened 2021-06-01 14:53 UTC by Samweli

Fixes https://github.com/ConservationInternational/trends.earth/issues/407

Adds a dataset details dialog that shows datasets information along with the details of the algorithm used to create the dataset.

Screenshot showing the dataset details dialog
![dataset_details_dialog](https://user-images.githubusercontent.com/2663775/120344411-3a46c700-c302-11eb-9bd9-be61703700aa.png)

2021-06-13 23:07 UTC, ricardogsilva commented
@Samweli 

please fix the reported conflicts and let me know whether this is ready for a review

2021-06-14 03:26 UTC, Samweli commented
> @Samweli 
> 
> please fix the reported conflicts and let me know whether this is ready for a review

sure @ricardogsilva working on this.

2021-06-14 07:04 UTC, Samweli commented
@ricardogsilva I have fixed the conflicts.

2021-06-14 16:18 UTC, ricardogsilva commented
@Samweli this does not include the latest changes, i.e. it is missing `areaofinterest.py` module, so it does not run. Please update it

2021-06-14 19:02 UTC, Samweli commented
> @Samweli this does not include the latest changes, i.e. it is missing `areaofinterest.py` module, so it does not run. Please update it

right, done!

2021-06-14 20:53 UTC, ricardogsilva requested changes
It is a good start, but I'd like to request the following modifications:

- [x] Make the dialogue be modal and provide it a parent. It should behave like the other dialogues

- [x] The dialogue is too tall and too narrow, make the default size wider, but smaller

- [x] Do not repeat information:

   - [x] task name shows up twice

   - [x] task status also shows up twice

- [x] Export as a zip should show its message in the details dialogue - otherwise it is difficult to see it, as the dialogue is likely in front of the QGIS main window

- [x] Add a button next to the task path to allow opening it with the file manager
- [x] Add the same icons used in the dataset list to the buttons used for deleting and loading a dataset.
- [x] Add an icon to the button that generates a zip
- [x] Zip file uses a name of `dataset.zip` - this is too generic. Name it similar to the name of the json file
- [x] Zip contents only include the tif output. Also put the json file in there
- [x] Zip file should go into a different directory - lets use a directory named `{trends_earth_base_dir}/exported`

2021-06-15 22:00 UTC, Samweli commented
@ricardogsilva thanks, I have updated the PR addressing all comments except for the below one

> * [ ]  Make the dialogue be modal and provide it a parent. It should behave like the other dialogues

I have had challenges in past and up till now, when I provide a parent to the dialog, the dialog can disappear without getting closed.

2021-06-15 22:34 UTC, ricardogsilva requested changes
Functionality-wise it seems to be working OK.

Please adjust the code according to my comments and then I'll be +1 for merging

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +WidgetDatasetItemDetailsUi, _ = uic.loadUiType(
Please put the details dialog code in its own file. The `jobs.mvc` module is good as it is.

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +class DatasetActions:
Please do not overuse inheritance (and even more severe, multiple inheritance). IMO this is a fault of the original plugin. It makes the code harder to read and there is no clear advantage in this case.

In this case we do not need this `DatasetActions` class at all, as its methods can go directly in the `DatasetDetailsDialog` class.

Just to clarify, I am not against using inheritance, where it makes sense. There is currently no other code that needs the methods offered by `DatasetActions` so there is no need for this kind of abstraction.

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +class DatasetEditorWidget(QtWidgets.QWidget, DatasetActions,  WidgetDatasetItemUi):
Please rename this to `DatasetEditorDialogue` and make it a subclass of `QtWidgets.QDialog`.

Also, as mentioned above:

- put this code in another file, not on `jobs.mvc`
- `DatasetActions` should not be a superclass to this one. Merge it into this

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +    def __delete_dataset(self):
Please do not use this kind of naming scheme for methods. Don't use double underscores for naming methods that are not Python special methods. I am aware some devs do it to signal that this is a private method. The usefulness of this in a language like Python can be debated, but for brevity, for this project, lets just no use it.

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +        self.close()
make this class be a `QDialog` and use `self.accept` instead of `self.close`

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +        except Exception:
Always avoid using the generic `Exception` in a try block. Check which exceptions can happen and write code to guard against those.

If we ever get some unforeseen exception we fix the code

2021-06-15 22:34 UTC, ricardogsilva commented on LDMP/jobs/mvc.py
> +        result = DatasetDetailsWidget(self.job).exec_()
make the qgis main window become the parent of this dialogue.

2021-06-18 10:58 UTC, ricardogsilva approved these changes
LGTM!

2021-06-18 10:58 UTC, merged